=== disclose/diodb/program-list-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "program_name": {
        "type": "string"
      },
      "policy_url": {
        "type": "string",
        "format": "uri"
      },
      "policy_url_status": {
        "type": "string",
        "enum": [
          "alive",
          "dead"
        ]
      },
      "contact_url": {
        "type": "string",
        "format": "uri"
      },
      "contact_email": {
        "type": "string",
        "format": "email"
      },
      "launch_date": {
        "anyOf": [
          {
            "type": "string",
            "enum": [
              ""
            ]
          },
          {
            "type": "string",
            "format": "date"
          }
        ]
      },
      "offers_bounty": {
        "type": "string",
        "enum": [
          "yes",
          "no",
          "partial"
        ]
      },
      "offers_swag": {
        "type": "boolean"
      },
      "hall_of_fame": {
        "type": "string",
        "format": "uri"
      },
      "safe_harbor": {
        "type": "string",
        "enum": [
          "full",
          "partial",
          "none"
        ]
      },
      "public_disclosure": {
        "type": "string",
        "enum": [
          "nda",
          "discretionary",
          "co-ordinated",
          ""
        ]
      },
      "disclosure_timeline_days": {
        "type": "number",
        "minimum": 0
      },
      "pgp_key": {
        "type": "string",
        "format": "uri"
      },
      "hiring": {
        "type": "string",
        "format": "uri"
      },
      "securitytxt_url": {
        "type": "string",
        "format": "uri"
      },
      "preferred_languages": {
        "type": "string"
      }
    },
    "required": [
      "policy_url",
      "public_disclosure"
    ],
    "anyOf": [
      {
        "required": [
          "contact_url"
        ]
      },
      {
        "required": [
          "contact_email"
        ]
      }
    ]
  }
}

=== disclose/diodb/programs/c/circleci_com.json
{
    "contact_url": "https://circleci.com/security/#concerns",
    "hall_of_fame": "",
    "hiring": "",
    "launch_date": "",
    "offers_bounty": "no",
    "offers_swag": true,
    "pgp_key": "",
    "policy_url": "https://circleci.com/security/",
    "policy_url_status": "alive",
    "preferred_languages": "",
    "program_name": "CircleCi",
    "public_disclosure": "",
    "safe_harbor": "none",
    "securitytxt_url": ""
}

=== disclose/diodb/programs/w/www_avira_com.json
{
    "contact_email": "vulnerabilities@avira.com",
    "hall_of_fame": "",
    "hiring": "",
    "launch_date": "",
    "offers_bounty": "yes",
    "offers_swag": false,
    "pgp_key": "",
    "policy_url": "https://www.avira.com/en/support-vulnerability",
    "policy_url_status": "alive",
    "preferred_languages": "",
    "program_name": "Avira",
    "public_disclosure": "",
    "safe_harbor": "none",
    "securitytxt_url": ""
}

=== disclose/diodb/programs/w/www_huawei_com.json
{
    "contact_email": "psirt@huawei.com",
    "hall_of_fame": "",
    "hiring": "",
    "launch_date": "",
    "offers_bounty": "no",
    "offers_swag": false,
    "pgp_key": "",
    "policy_url": "https://www.huawei.com/en/psirt/report-vulnerabilities",
    "policy_url_status": "alive",
    "preferred_languages": "",
    "program_name": "Huawei",
    "public_disclosure": "",
    "safe_harbor": "none",
    "securitytxt_url": ""
}

=== disclose/diodb/programs/s/shieldox_security.json
{
    "contact_url": "https://hackerone.com/shieldox_security",
    "hall_of_fame": "",
    "hiring": "",
    "launch_date": "",
    "offers_bounty": "no",
    "offers_swag": false,
    "pgp_key": "",
    "policy_url": "https://hackerone.com/shieldox_security",
    "policy_url_status": "alive",
    "preferred_languages": "",
    "program_name": "Shieldox Security LTD",
    "public_disclosure": "",
    "safe_harbor": "none",
    "securitytxt_url": ""
}

=== disclose/diodb/programs/s/studo_com.json
{
    "contact_email": "security@moshbit.com",
    "hall_of_fame": "",
    "hiring": "",
    "launch_date": "",
    "offers_bounty": "yes",
    "offers_swag": false,
    "pgp_key": "",
    "policy_url": "https://studo.com/at/security",
    "policy_url_status": "alive",
    "preferred_languages": "",
    "program_name": "Studo",
    "public_disclosure": "",
    "safe_harbor": "partial",
    "securitytxt_url": ""
}

=== disclose/diodb/programs/g/ghostscript_com.json
{
    "contact_url": "https://artifex.com/legal/security/",
    "hall_of_fame": "",
    "hiring": "",
    "launch_date": "",
    "offers_bounty": "yes",
    "offers_swag": false,
    "pgp_key": "",
    "policy_url": "https://ghostscript.com/Bug_bounty_program.html",
    "policy_url_status": "alive",
    "preferred_languages": "",
    "program_name": "Ghostscript",
    "public_disclosure": "",
    "safe_harbor": "none",
    "securitytxt_url": ""
}

=== disclose/diodb/programs/w/www_jenkins_io.json
{
    "contact_url": "https://issues.jenkins.io/browse/SECURITY",
    "hall_of_fame": "",
    "hiring": "",
    "launch_date": "",
    "offers_bounty": "no",
    "offers_swag": false,
    "pgp_key": "",
    "policy_url": "https://www.jenkins.io/security/reporting/",
    "policy_url_status": "alive",
    "preferred_languages": "",
    "program_name": "Jenkins",
    "public_disclosure": "",
    "safe_harbor": "none",
    "securitytxt_url": ""
}

=== disclose/diodb/programs/w/www_lookout_com.json
{
    "contact_email": "security@lookout.com",
    "hall_of_fame": "",
    "hiring": "",
    "launch_date": "",
    "offers_bounty": "no",
    "offers_swag": false,
    "pgp_key": "",
    "policy_url": "https://www.lookout.com/legal/responsible-disclosure",
    "policy_url_status": "alive",
    "preferred_languages": "",
    "program_name": "Lookout",
    "public_disclosure": "",
    "safe_harbor": "partial",
    "securitytxt_url": ""
}
