=== disclose/diodb/program-list-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "program_name": {
        "type": "string"
      },
      "policy_url": {
        "type": "string",
        "format": "uri"
      },
      "policy_url_status": {
        "type": "string",
        "enum": [
          "alive",
          "dead"
        ]
      },
      "contact_url": {
        "type": "string",
        "format": "uri"
      },
      "contact_email": {
        "type": "string",
        "format": "email"
      },
      "launch_date": {
        "anyOf": [
          {
            "type": "string",
            "enum": [
              ""
            ]
          },
          {
            "type": "string",
            "format": "date"
          }
        ]
      },
      "offers_bounty": {
        "type": "string",
        "enum": [
          "yes",
          "no",
          "partial"
        ]
      },
      "offers_swag": {
        "type": "boolean"
      },
      "hall_of_fame": {
        "type": "string",
        "format": "uri"
      },
      "safe_harbor": {
        "type": "string",
        "enum": [
          "full",
          "partial",
          "none"
        ]
      },
      "public_disclosure": {
        "type": "string",
        "enum": [
          "nda",
          "discretionary",
          "co-ordinated",
          ""
        ]
      },
      "disclosure_timeline_days": {
        "type": "number",
        "minimum": 0
      },
      "pgp_key": {
        "type": "string",
        "format": "uri"
      },
      "hiring": {
        "type": "string",
        "format": "uri"
      },
      "securitytxt_url": {
        "type": "string",
        "format": "uri"
      },
      "preferred_languages": {
        "type": "string"
      }
    },
    "required": [
      "policy_url",
      "public_disclosure"
    ],
    "anyOf": [
      {
        "required": [
          "contact_url"
        ]
      },
      {
        "required": [
          "contact_email"
        ]
      }
    ]
  }
}

=== disclose/diodb/programs/a/app_trovisio_com.json
{
    "contact_email": "info@trovisio.com",
    "hall_of_fame": "",
    "hiring": "",
    "launch_date": "",
    "offers_bounty": "no",
    "offers_swag": false,
    "pgp_key": "",
    "policy_url": "https://app.trovisio.com/legal?disclosure=disclosure",
    "policy_url_status": "alive",
    "preferred_languages": "",
    "program_name": "Trovisio",
    "public_disclosure": "",
    "safe_harbor": "none",
    "securitytxt_url": ""
}

=== disclose/diodb/programs/g/global_bose_com.json
{
    "contact_email": "privacyandsecurity@bose.com",
    "hall_of_fame": "",
    "hiring": "",
    "launch_date": "",
    "offers_bounty": "yes",
    "offers_swag": false,
    "pgp_key": "",
    "policy_url": "https://global.bose.com/en_us/product_security_vulnerability_response.html",
    "policy_url_status": "alive",
    "preferred_languages": "",
    "program_name": "Bose",
    "public_disclosure": "",
    "safe_harbor": "partial",
    "securitytxt_url": ""
}

=== disclose/diodb/programs/a/athento_zendesk_com.json
{
    "contact_url": "https://athento.zendesk.com/hc/es/articles/360023151053",
    "hall_of_fame": "",
    "hiring": "",
    "launch_date": "",
    "offers_bounty": "no",
    "offers_swag": false,
    "pgp_key": "",
    "policy_url": "https://athento.zendesk.com/hc/es/articles/360010484720",
    "policy_url_status": "alive",
    "preferred_languages": "",
    "program_name": "Athento",
    "public_disclosure": "",
    "safe_harbor": "none",
    "securitytxt_url": ""
}

=== disclose/diodb/programs/w/www_united_com.json
{
    "contact_email": "bugbounty@united.com",
    "hall_of_fame": "",
    "hiring": "",
    "launch_date": "",
    "offers_bounty": "yes",
    "offers_swag": false,
    "pgp_key": "",
    "policy_url": "https://www.united.com/web/en-US/content/contact/bugbounty.aspx",
    "policy_url_status": "alive",
    "preferred_languages": "",
    "program_name": "United Airlines",
    "public_disclosure": "",
    "safe_harbor": "none",
    "securitytxt_url": ""
}

=== disclose/diodb/programs/e/en_internetwache_org.json
{
    "contact_email": "security@internetwache.org",
    "hall_of_fame": "",
    "hiring": "",
    "launch_date": "",
    "offers_bounty": "no",
    "offers_swag": false,
    "pgp_key": "",
    "policy_url": "https://en.internetwache.org/security/",
    "policy_url_status": "alive",
    "preferred_languages": "",
    "program_name": "Internetwache",
    "public_disclosure": "",
    "safe_harbor": "partial",
    "securitytxt_url": ""
}

=== disclose/diodb/programs/b/bugbounty_zoho_com.json
{
    "contact_url": "https://bugbounty.zoho.com/submit",
    "hall_of_fame": "",
    "hiring": "",
    "launch_date": "",
    "offers_bounty": "yes",
    "offers_swag": false,
    "pgp_key": "",
    "policy_url": "https://bugbounty.zoho.com/bb/info#guide",
    "policy_url_status": "alive",
    "preferred_languages": "",
    "program_name": "Zoho",
    "public_disclosure": "",
    "safe_harbor": "none",
    "securitytxt_url": ""
}

=== disclose/diodb/programs/b/blog_getambassador_io.json
{
    "contact_email": "secalert@datawire.io",
    "hall_of_fame": "",
    "hiring": "",
    "launch_date": "",
    "offers_bounty": "no",
    "offers_swag": true,
    "pgp_key": "",
    "policy_url": "https://blog.getambassador.io/security-in-ambassador-a-risk-based-approach-fd24e364ea84",
    "policy_url_status": "alive",
    "preferred_languages": "",
    "program_name": "GetAmbassador",
    "public_disclosure": "",
    "safe_harbor": "partial",
    "securitytxt_url": ""
}

=== disclose/diodb/programs/w/www_chargify_com.json
{
    "contact_email": "security@chargify.com",
    "hall_of_fame": "",
    "hiring": "",
    "launch_date": "",
    "offers_bounty": "no",
    "offers_swag": false,
    "pgp_key": "",
    "policy_url": "https://www.chargify.com/security/",
    "policy_url_status": "alive",
    "preferred_languages": "",
    "program_name": "Chargify",
    "public_disclosure": "",
    "safe_harbor": "none",
    "securitytxt_url": ""
}
