=== disclose/diodb/program-list-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "array",
  "items": {
    "type": "object",
    "properties": {
      "program_name": {
        "type": "string"
      },
      "policy_url": {
        "type": "string",
        "format": "uri"
      },
      "policy_url_status": {
        "type": "string",
        "enum": [
          "alive",
          "dead"
        ]
      },
      "contact_url": {
        "type": "string",
        "format": "uri"
      },
      "contact_email": {
        "type": "string",
        "format": "email"
      },
      "launch_date": {
        "anyOf": [
          {
            "type": "string",
            "enum": [
              ""
            ]
          },
          {
            "type": "string",
            "format": "date"
          }
        ]
      },
      "offers_bounty": {
        "type": "string",
        "enum": [
          "yes",
          "no",
          "partial"
        ]
      },
      "offers_swag": {
        "type": "boolean"
      },
      "hall_of_fame": {
        "type": "string",
        "format": "uri"
      },
      "safe_harbor": {
        "type": "string",
        "enum": [
          "full",
          "partial",
          "none"
        ]
      },
      "public_disclosure": {
        "type": "string",
        "enum": [
          "nda",
          "discretionary",
          "co-ordinated",
          ""
        ]
      },
      "disclosure_timeline_days": {
        "type": "number",
        "minimum": 0
      },
      "pgp_key": {
        "type": "string",
        "format": "uri"
      },
      "hiring": {
        "type": "string",
        "format": "uri"
      },
      "securitytxt_url": {
        "type": "string",
        "format": "uri"
      },
      "preferred_languages": {
        "type": "string"
      }
    },
    "required": [
      "policy_url",
      "public_disclosure"
    ],
    "anyOf": [
      {
        "required": [
          "contact_url"
        ]
      },
      {
        "required": [
          "contact_email"
        ]
      }
    ]
  }
}

=== disclose/diodb/programs/g/gay_capital.json
{
    "contact_email": "Support@Gay.Capital",
    "hall_of_fame": "",
    "hiring": "",
    "launch_date": "",
    "offers_bounty": "no",
    "offers_swag": false,
    "pgp_key": "",
    "policy_url": "https://gay.capital/docs/bugbounty",
    "policy_url_status": "alive",
    "preferred_languages": "",
    "program_name": "Gay.Capital",
    "public_disclosure": "",
    "safe_harbor": "full",
    "securitytxt_url": ""
}

=== disclose/diodb/programs/w/www_braintreepayments_com.json
{
    "contact_email": "ppbugbounty@paypal.com",
    "hall_of_fame": "",
    "hiring": "",
    "launch_date": "",
    "offers_bounty": "no",
    "offers_swag": false,
    "pgp_key": "",
    "policy_url": "https://www.braintreepayments.com/developers/disclosure",
    "policy_url_status": "alive",
    "preferred_languages": "",
    "program_name": "Braintree",
    "public_disclosure": "",
    "safe_harbor": "none",
    "securitytxt_url": ""
}

=== disclose/diodb/programs/c/cybersecurity_att_com.json
{
    "contact_url": "https://hackerone.com/alienvault_security",
    "hall_of_fame": "",
    "hiring": "",
    "launch_date": "",
    "offers_bounty": "no",
    "offers_swag": false,
    "pgp_key": "",
    "policy_url": "https://cybersecurity.att.com/documentation/usm-appliance/system-overview/how-to-submit-a-security-issue-to-alienvault.htm",
    "policy_url_status": "dead",
    "preferred_languages": "",
    "program_name": "Alienvault",
    "public_disclosure": "",
    "safe_harbor": "none",
    "securitytxt_url": ""
}

=== disclose/diodb/programs/w/www_independer_nl.json
{
    "contact_email": "beveiliging@independer.nl",
    "hall_of_fame": "",
    "hiring": "",
    "launch_date": "",
    "offers_bounty": "yes",
    "offers_swag": false,
    "pgp_key": "",
    "policy_url": "https://www.independer.nl/algemeen/info/responsible-disclosure.aspx",
    "policy_url_status": "alive",
    "preferred_languages": "",
    "program_name": "Independer",
    "public_disclosure": "",
    "safe_harbor": "partial",
    "securitytxt_url": ""
}

=== disclose/diodb/programs/u/underarmour.json
{
    "contact_url": "https://bugcrowd.com/underarmour/report",
    "hall_of_fame": "",
    "hiring": "",
    "launch_date": "",
    "offers_bounty": "no",
    "offers_swag": false,
    "pgp_key": "",
    "policy_url": "https://bugcrowd.com/underarmour",
    "policy_url_status": "alive",
    "preferred_languages": "",
    "program_name": "UNDER ARMOUR",
    "public_disclosure": "",
    "safe_harbor": "partial",
    "securitytxt_url": ""
}

=== disclose/diodb/programs/h/hubspot.json
{
    "contact_url": "https://bugcrowd.com/hubspot/report",
    "hall_of_fame": "",
    "hiring": "",
    "launch_date": "",
    "offers_bounty": "no",
    "offers_swag": false,
    "pgp_key": "",
    "policy_url": "https://bugcrowd.com/hubspot",
    "policy_url_status": "alive",
    "preferred_languages": "",
    "program_name": "HubSpot",
    "public_disclosure": "",
    "safe_harbor": "partial",
    "securitytxt_url": ""
}

=== disclose/diodb/programs/e/en_altervista_org.json
{
    "contact_url": "https://en.altervista.org/feedback.php?who=feedback",
    "hall_of_fame": "",
    "hiring": "",
    "launch_date": "",
    "offers_bounty": "no",
    "offers_swag": false,
    "pgp_key": "",
    "policy_url": "https://en.altervista.org/feedback.php?who=feedback",
    "policy_url_status": "alive",
    "preferred_languages": "",
    "program_name": "Altervista",
    "public_disclosure": "",
    "safe_harbor": "none",
    "securitytxt_url": ""
}

=== disclose/diodb/programs/n/naspers.json
{
    "contact_url": "https://bugcrowd.com/naspers/report",
    "hall_of_fame": "",
    "hiring": "",
    "launch_date": "",
    "offers_bounty": "no",
    "offers_swag": false,
    "pgp_key": "",
    "policy_url": "https://bugcrowd.com/naspers",
    "policy_url_status": "alive",
    "preferred_languages": "",
    "program_name": "Naspers",
    "public_disclosure": "",
    "safe_harbor": "full",
    "securitytxt_url": ""
}
